general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cfOrg: "eeb195f2trial"
    cfSpace: 'dev'
    cfApiEndpoint: https://api.cf.us10-001.hana.ondemand.com
    cfCredentialsId: 'CF_CREDENTIALSID'
